/* AUTO-GENERATED by build.js — 直接編集しないこと。編集は app.src.jsx を変更し node build.js を再実行 */
const ERROR_CONFIG = {
  PROJECT_ID: "ERROR_NO_CONFIG",
  TOP_HEADING: "System Error",
  TOP_DESCRIPTION: "設定ファイル (config.js) が読み込めません。\nファイルが存在しているか確認してください。",
  QUESTIONS: [{
    id: 'error',
    type: 'text',
    question: '設定ファイルが読み込めませんでした。管理者に連絡してください。',
    placeholder: '入力できません'
  }]
};
const CONFIG = typeof WSP_CONFIG !== 'undefined' ? WSP_CONFIG : ERROR_CONFIG;
const {
  useState,
  useEffect,
  useRef
} = React;
const QUESTIONS = CONFIG.QUESTIONS;
const ChevronRight = ({
  className
}) => React.createElement("svg", {
  className: className,
  xmlns: "http://www.w3.org/2000/svg",
  width: "24",
  height: "24",
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: "1.5",
  strokeLinecap: "round",
  strokeLinejoin: "round"
}, React.createElement("polyline", {
  points: "9 18 15 12 9 6"
}));
function App() {
  const [currentStep, setCurrentStep] = useState(-1);
  const [answers, setAnswers] = useState({});
  const [isAnimating, setIsAnimating] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [showOrientation, setShowOrientation] = useState(false);
  const handleNext = (force = false) => {
    if (isAnimating) return;
    if (force !== true && currentStep >= 0 && currentStep < QUESTIONS.length) {
      const qId = QUESTIONS[currentStep].id;
      const val = answers[qId];
      if (val === undefined || val === null) return;
      if (typeof val === 'string' && !val.trim()) return;
      if (Array.isArray(val) && val.length === 0) return;
      if (typeof val === 'object' && !Array.isArray(val)) {
        if (!val.current || !val.ideal) return;
      }
    }
    setIsAnimating(true);
    setTimeout(() => {
      setCurrentStep(prev => prev + 1);
      setIsAnimating(false);
    }, 600);
  };
  const handleAnswer = (questionId, value) => {
    setAnswers(prev => ({
      ...prev,
      [questionId]: value
    }));
    const q = QUESTIONS.find(q => q.id === questionId);
    if (q && (q.type === 'choice' || q.type === 'scale')) {
      setTimeout(() => handleNext(true), 500);
    }
  };
  const handleMultiToggle = (questionId, value) => {
    setAnswers(prev => {
      const current = Array.isArray(prev[questionId]) ? prev[questionId] : [];
      const exists = current.includes(value);
      return {
        ...prev,
        [questionId]: exists ? current.filter(v => v !== value) : [...current, value]
      };
    });
  };
  const handleLevelSelect = (questionId, kind, value) => {
    setAnswers(prev => {
      const obj = prev[questionId] && typeof prev[questionId] === 'object' && !Array.isArray(prev[questionId]) ? prev[questionId] : {};
      return {
        ...prev,
        [questionId]: {
          ...obj,
          [kind]: value
        }
      };
    });
  };
  const handleSubmit = async () => {
    setIsSubmitting(true);
    const URL = "https://script.google.com/macros/s/AKfycbz7H155CDdhRkAhZ0p-gzgAhadvQdIdPV6rD8poBL3ZiTuLzzDBcwsbaFiP4ut3j_4/exec";
    const formattedAnswers = {
      "日時": new Date().toLocaleString('ja-JP')
    };
    QUESTIONS.forEach(q => {
      let headerText = q.question;
      if (q.type === 'scale') {
        headerText += ` (1:${q.minLabel} - ${q.scaleMax}:${q.maxLabel})`;
      }
      let value = answers[q.id];
      if (Array.isArray(value)) {
        value = value.join(' | ');
      } else if (value && typeof value === 'object') {
        value = `現状: ${value.current || '(未選択)'}　／　3年後の理想: ${value.ideal || '(未選択)'}`;
      }
      formattedAnswers[headerText] = value || "";
    });
    const payload = {
      projectId: CONFIG.PROJECT_ID,
      surveyKind: CONFIG.SURVEY_KIND || "Individual",
      answers: formattedAnswers
    };
    try {
      await fetch(URL, {
        method: "POST",
        mode: "no-cors",
        cache: "no-cache",
        headers: {
          "Content-Type": "text/plain"
        },
        body: JSON.stringify(payload)
      });
      setTimeout(() => handleNext(), 500);
    } catch (e) {
      console.error("Fetch Error:", e);
      alert("送信中にネットワークエラーが発生しました。");
    } finally {
      setIsSubmitting(false);
    }
  };
  const renderStart = () => React.createElement("div", {
    className: `transition-all duration-1000 transform ${isAnimating ? 'opacity-0 scale-95' : 'opacity-100 scale-100'} flex flex-col items-center justify-center w-full max-w-6xl mx-auto px-6 flex-1 text-center`
  }, React.createElement("h1", {
    className: "text-[4.5rem] sm:text-[7rem] md:text-[9.5rem] lg:text-[12rem] font-light tracking-tighter mb-4 leading-none"
  }, React.createElement("span", {
    className: "text-gradient block"
  }, "WSP Radar")), React.createElement("h2", {
    className: `text-base sm:text-lg md:text-2xl font-light tracking-[0.2em] md:tracking-[0.3em] mb-12 md:mb-16 opacity-90 ${CONFIG === ERROR_CONFIG ? 'text-red-400 font-bold' : 'text-art-text'}`
  }, CONFIG.TOP_HEADING), React.createElement("p", {
    style: {
      textShadow: '0 1px 2px rgba(0,0,0,0.95), 0 0 14px rgba(0,0,0,0.7), 0 0 28px rgba(0,0,0,0.45)'
    },
    className: `max-w-2xl mx-auto font-light leading-[2.2] tracking-widest text-sm md:text-lg mb-16 text-center ${CONFIG === ERROR_CONFIG ? 'text-red-300' : 'text-gray-300'}`
  }, CONFIG.TOP_DESCRIPTION.split('\n').map((line, index) => React.createElement(React.Fragment, {
    key: index
  }, line, React.createElement("br", {
    className: "hidden md:block"
  })))), CONFIG !== ERROR_CONFIG && React.createElement("button", {
    onClick: () => {
      if (isAnimating) return;
      setIsAnimating(true);
      setTimeout(() => {
        setShowOrientation(true);
        setIsAnimating(false);
      }, 600);
    },
    className: "group flex items-center justify-center gap-4 border border-art-accentYellow text-art-accentYellow px-14 py-4 uppercase tracking-[0.3em] text-sm md:text-base transition-all duration-700 hover:bg-art-accentYellow hover:text-art-bg hover:scale-105"
  }, "START SURVEY"));
  const renderOrientation = () => React.createElement("div", {
    className: `transition-all duration-700 ease-in-out transform ${isAnimating ? 'opacity-0 translate-x-10' : 'opacity-100 translate-x-0'} w-full max-w-3xl mx-auto px-6 sm:px-10 flex-1 flex flex-col justify-center`
  }, React.createElement("div", {
    className: "w-full"
  }, React.createElement("span", {
    className: "text-art-accentPeach text-xs uppercase mb-2 tracking-widest text-center md:text-left block"
  }, "How to Answer"), React.createElement("h2", {
    className: "text-xl md:text-2xl font-normal text-art-text mb-4 md:mb-5 leading-snug tracking-wide"
  }, "\u3053\u306E\u30B5\u30FC\u30D9\u30A4\u306E\u56DE\u7B54\u65B9\u6CD5"), React.createElement("p", {
    className: "text-sm md:text-base text-art-muted leading-relaxed mb-5"
  }, "\u5404\u8A2D\u554F\u3067\u306F\u30015\u6BB5\u968E\u306E\u9078\u629E\u80A2\u306E\u4E2D\u304B\u3089", React.createElement("span", {
    className: "text-art-accentYellow font-bold"
  }, "\u300C\u73FE\u72B6\u300D"), "\u3068", React.createElement("span", {
    className: "text-art-accentPeach font-bold"
  }, "\u300C3\u5E74\u5F8C\u306E\u7406\u60F3\u300D"), "\u30921\u3064\u305A\u3064\u9078\u3093\u3067\u3044\u305F\u3060\u304D\u307E\u3059\u3002"), React.createElement("div", {
    className: "border border-art-border/50 px-4 md:px-6 py-4 md:py-5 mb-5"
  }, React.createElement("div", {
    className: "text-[10px] tracking-widest uppercase text-art-muted/70 mb-3"
  }, "\u4F8B\uFF1A\u300C\u5E79\u90E8\u5C64\u306E\u69CB\u6210\u300D\u306E\u5834\u5408"), React.createElement("div", {
    className: "flex items-center justify-end gap-3 mb-2 text-[10px] tracking-widest uppercase"
  }, React.createElement("span", {
    className: "w-10 text-center text-art-accentYellow"
  }, "\u73FE\u72B6"), React.createElement("span", {
    className: "w-10 text-center text-art-accentPeach"
  }, "3\u5E74\u5F8C")), React.createElement("div", {
    className: "space-y-1.5 text-xs md:text-sm"
  }, [{
    txt: "1. 日本人駐在員が中心となり…",
    cur: false,
    ideal: false
  }, {
    txt: "2. 日本人が主軸を担いつつ…",
    cur: true,
    ideal: false,
    note: "← 現状はこちら"
  }, {
    txt: "3. 部門の特性に応じて…",
    cur: false,
    ideal: false
  }, {
    txt: "4. 多くの主要ポストを現地人材…",
    cur: false,
    ideal: true,
    note: "← 3年後の理想はこちら"
  }, {
    txt: "5. 社長を含め、全主要ポスト…",
    cur: false,
    ideal: false
  }].map((row, i) => React.createElement("div", {
    key: i,
    className: "flex items-center gap-3"
  }, React.createElement("span", {
    className: "flex-1 text-art-muted"
  }, row.txt), row.note && React.createElement("span", {
    className: "text-[10px] text-art-muted/70 hidden md:inline"
  }, row.note), React.createElement("span", {
    className: `w-5 h-5 md:w-6 md:h-6 rounded-full border flex items-center justify-center text-[9px] ${row.cur ? 'bg-art-accentYellow border-art-accentYellow text-art-bg font-bold' : 'border-art-border'}`
  }, row.cur ? '■' : ''), React.createElement("span", {
    className: `w-5 h-5 md:w-6 md:h-6 rounded-full border flex items-center justify-center text-[9px] ${row.ideal ? 'bg-art-accentPeach border-art-accentPeach text-art-bg font-bold' : 'border-art-border'}`
  }, row.ideal ? '◆' : ''))))), React.createElement("p", {
    className: "text-xs md:text-sm text-art-muted/80 italic mb-6"
  }, "\u203B \u6DF1\u304F\u60A9\u307E\u305A\u3001\u6700\u521D\u306B\u601D\u3044\u6D6E\u304B\u3093\u3060\u611F\u899A\u3067\u304A\u9078\u3073\u304F\u3060\u3055\u3044\u3002"), React.createElement("div", {
    className: "flex justify-end"
  }, React.createElement("button", {
    onClick: () => {
      if (isAnimating) return;
      setIsAnimating(true);
      setTimeout(() => {
        setShowOrientation(false);
        setCurrentStep(0);
        setIsAnimating(false);
      }, 600);
    },
    className: "px-10 py-3 border border-art-accentYellow text-art-accentYellow hover:bg-art-accentYellow hover:text-art-bg transition-all uppercase tracking-widest text-sm"
  }, "\u56DE\u7B54\u3092\u59CB\u3081\u308B"))));
  const renderQuestion = (q, i) => React.createElement("div", {
    className: `transition-all duration-700 ease-in-out transform ${isAnimating ? 'opacity-0 translate-x-10' : 'opacity-100 translate-x-0'} w-full max-w-3xl mx-auto px-6 sm:px-10 flex-1 flex flex-col justify-center`
  }, React.createElement("div", {
    className: "w-full"
  }, React.createElement("div", {
    className: "flex items-baseline gap-2 mb-2 justify-center md:justify-start"
  }, React.createElement("span", {
    className: "text-art-accentPeach text-xs uppercase tracking-widest"
  }, "Question ", String(i + 1).padStart(2, '0')), React.createElement("span", {
    className: "text-art-muted/70 text-[10px] uppercase tracking-widest"
  }, "\uFF0F ", String(QUESTIONS.length).padStart(2, '0'))), React.createElement("div", {
    className: "w-full h-[3px] bg-art-border/30 mb-3 md:mb-4 overflow-hidden"
  }, React.createElement("div", {
    className: "h-full bg-gradient-to-r from-art-accentYellow via-art-accentPeach to-art-accentGreen transition-all duration-700 ease-out",
    style: {
      width: `${Math.round((i + 1) / QUESTIONS.length * 100)}%`
    }
  })), React.createElement("h2", {
    className: "text-base md:text-xl font-light text-art-text mb-4 md:mb-6 leading-snug tracking-wide text-center md:text-left"
  }, q.question), q.type === 'choice' && React.createElement("div", {
    className: "space-y-1.5 md:space-y-2"
  }, q.options.map((opt, idx) => React.createElement("button", {
    key: idx,
    onClick: () => handleAnswer(q.id, opt.label),
    className: `w-full text-left px-3 md:px-4 py-2 md:py-2.5 border text-xs md:text-sm leading-snug transition-all ${answers[q.id] === opt.label ? 'border-art-accentPeach bg-art-accentPeach/10 text-art-accentPeach' : 'border-art-border hover:border-art-accentYellow/50'}`
  }, opt.label))), q.type === 'levels' && React.createElement("div", {
    className: "w-full"
  }, React.createElement("p", {
    className: "text-[10px] md:text-xs text-art-muted/70 italic mb-2 text-center md:text-left"
  }, "\u203B\u5B8C\u5168\u306B\u5F53\u3066\u306F\u307E\u308B\u9078\u629E\u80A2\u304C\u306A\u3044\u5834\u5408\u306F\u3001\u611F\u899A\u306B\u6700\u3082\u8FD1\u3044\u3082\u306E\u3092\u304A\u9078\u3073\u304F\u3060\u3055\u3044\u3002"), React.createElement("div", {
    className: "flex items-center justify-end gap-3 md:gap-4 mb-2 text-[10px] tracking-widest uppercase"
  }, React.createElement("span", {
    className: "w-10 md:w-12 text-center text-art-accentYellow font-bold"
  }, "\u73FE\u72B6"), React.createElement("span", {
    className: "w-10 md:w-12 text-center text-art-accentPeach font-bold"
  }, "3\u5E74\u5F8C")), React.createElement("div", {
    className: "flex gap-2 md:gap-3 items-stretch"
  }, q.axis && React.createElement("div", {
    className: "flex flex-col w-16 md:w-24 flex-shrink-0 text-center relative"
  }, React.createElement("div", {
    className: "flex flex-col items-center justify-center min-h-[44px] md:min-h-[52px]"
  }, React.createElement("span", {
    className: "text-art-accentYellow text-xs md:text-sm font-bold leading-none"
  }, "1 \u2191"), React.createElement("span", {
    className: "text-art-text text-[9px] md:text-[11px] leading-tight mt-1 px-0.5"
  }, q.axis.left)), React.createElement("div", {
    className: "flex-1 flex items-center justify-center min-h-[100px]"
  }, React.createElement("div", {
    className: "w-px h-full bg-gradient-to-b from-art-accentYellow/40 via-art-border to-art-accentPeach/40"
  })), React.createElement("div", {
    className: "flex flex-col items-center justify-center min-h-[44px] md:min-h-[52px]"
  }, React.createElement("span", {
    className: "text-art-text text-[9px] md:text-[11px] leading-tight px-0.5"
  }, q.axis.right), React.createElement("span", {
    className: "text-art-accentPeach text-xs md:text-sm font-bold leading-none mt-1"
  }, "\u2193 5"))), React.createElement("div", {
    className: "flex-1 space-y-1.5 md:space-y-2"
  }, q.options.map((opt, idx) => {
    const ans = answers[q.id] && typeof answers[q.id] === 'object' && !Array.isArray(answers[q.id]) ? answers[q.id] : {};
    const isCurrent = ans.current === opt.label;
    const isIdeal = ans.ideal === opt.label;
    const highlight = isCurrent || isIdeal;
    return React.createElement("div", {
      key: idx,
      className: `flex items-center gap-3 md:gap-4 px-3 md:px-4 py-2 md:py-2.5 border text-sm md:text-base leading-relaxed transition-all ${highlight ? 'border-art-accentPeach/60' : 'border-art-border'}`
    }, React.createElement("span", {
      className: "flex-1 text-art-text"
    }, opt.label), React.createElement("button", {
      onClick: () => handleLevelSelect(q.id, 'current', opt.label),
      className: `w-10 md:w-12 h-6 md:h-7 flex-shrink-0 flex items-center justify-center border rounded-full text-[10px] transition-all ${isCurrent ? 'bg-art-accentYellow border-art-accentYellow text-art-bg font-bold' : 'border-art-border hover:border-art-accentYellow'}`
    }, isCurrent ? '■' : '○'), React.createElement("button", {
      onClick: () => handleLevelSelect(q.id, 'ideal', opt.label),
      className: `w-10 md:w-12 h-6 md:h-7 flex-shrink-0 flex items-center justify-center border rounded-full text-[10px] transition-all ${isIdeal ? 'bg-art-accentPeach border-art-accentPeach text-art-bg font-bold' : 'border-art-border hover:border-art-accentPeach'}`
    }, isIdeal ? '◆' : '○'));
  }))), CONFIG !== ERROR_CONFIG && React.createElement("div", {
    className: "mt-4 md:mt-5 flex justify-end"
  }, React.createElement("button", {
    onClick: () => handleNext(true),
    disabled: !(answers[q.id] && typeof answers[q.id] === 'object' && answers[q.id].current && answers[q.id].ideal),
    className: "px-8 py-2.5 border border-art-text text-art-text hover:bg-art-text hover:text-art-bg transition-all disabled:opacity-20 uppercase tracking-widest text-sm"
  }, "NEXT"))), q.type === 'multiChoice' && React.createElement("div", {
    className: "w-full"
  }, React.createElement("div", {
    className: "space-y-1.5 md:space-y-2"
  }, q.options.map((opt, idx) => {
    const selected = Array.isArray(answers[q.id]) && answers[q.id].includes(opt.label);
    return React.createElement("button", {
      key: idx,
      onClick: () => handleMultiToggle(q.id, opt.label),
      className: `w-full text-left px-3 md:px-4 py-2 md:py-2.5 border text-xs md:text-sm leading-snug transition-all flex items-start gap-2 ${selected ? 'border-art-accentPeach bg-art-accentPeach/10 text-art-accentPeach' : 'border-art-border hover:border-art-accentYellow/50'}`
    }, React.createElement("span", {
      className: "inline-block flex-shrink-0 w-4 text-center"
    }, selected ? '◼' : '◻'), React.createElement("span", {
      className: "flex-1"
    }, opt.label));
  })), CONFIG !== ERROR_CONFIG && React.createElement("div", {
    className: "mt-3 md:mt-4 flex justify-end"
  }, React.createElement("button", {
    onClick: () => handleNext(true),
    disabled: !(Array.isArray(answers[q.id]) && answers[q.id].length > 0),
    className: "px-8 py-2.5 border border-art-text text-art-text hover:bg-art-text hover:text-art-bg transition-all disabled:opacity-20 uppercase tracking-widest text-sm"
  }, "NEXT"))), q.type === 'scale' && React.createElement("div", {
    className: "flex justify-between items-center gap-4 py-4 max-w-2xl mx-auto"
  }, React.createElement("span", {
    className: "text-xs opacity-50 uppercase tracking-widest text-art-muted"
  }, q.minLabel), React.createElement("div", {
    className: "flex gap-2 md:gap-3"
  }, [1, 2, 3, 4, 5].map(v => React.createElement("button", {
    key: v,
    onClick: () => handleAnswer(q.id, v),
    className: `w-10 h-10 md:w-14 md:h-14 rounded-full border text-lg font-light transition-all ${answers[q.id] === v ? 'border-art-accentPeach bg-art-accentPeach text-art-bg' : 'border-art-border hover:border-art-accentYellow'}`
  }, v))), React.createElement("span", {
    className: "text-xs opacity-50 uppercase tracking-widest text-art-muted"
  }, q.maxLabel)), q.type === 'text' && React.createElement("div", {
    className: "w-full"
  }, React.createElement("textarea", {
    autoFocus: true,
    ref: el => {
      if (el) {
        el.style.height = 'auto';
        el.style.height = el.scrollHeight + 'px';
      }
    },
    value: answers[q.id] || '',
    onChange: e => {
      setAnswers({
        ...answers,
        [q.id]: e.target.value
      });
      e.target.style.height = 'auto';
      e.target.style.height = e.target.scrollHeight + 'px';
    },
    rows: "1",
    className: "w-full bg-transparent border-b border-art-border pt-1 pb-2 text-xs md:text-sm leading-relaxed outline-none focus:border-art-accentPeach transition-colors resize-none overflow-hidden placeholder:text-art-muted/60",
    placeholder: q.placeholder,
    disabled: CONFIG === ERROR_CONFIG
  }), CONFIG !== ERROR_CONFIG && React.createElement("div", {
    className: "mt-3 md:mt-4 flex justify-end"
  }, React.createElement("button", {
    onClick: handleNext,
    disabled: !answers[q.id]?.trim(),
    className: "px-8 py-2.5 border border-art-text text-art-text hover:bg-art-text hover:text-art-bg transition-all disabled:opacity-20 uppercase tracking-widest text-sm"
  }, "NEXT")))));
  return React.createElement("div", {
    className: "min-h-screen relative flex flex-col w-full"
  }, React.createElement("div", {
    className: `radar-container ${currentStep === -1 && !showOrientation ? 'top-mode' : 'survey-mode'}`
  }, React.createElement("div", {
    className: "radar-sweep"
  }), React.createElement("div", {
    className: "radar-pulse-ring"
  })), React.createElement("main", {
    className: "flex-1 flex flex-col justify-center relative z-10 min-h-screen w-full py-10 md:py-12"
  }, currentStep === -1 && !showOrientation && renderStart(), currentStep === -1 && showOrientation && renderOrientation(), currentStep >= 0 && currentStep < QUESTIONS.length && renderQuestion(QUESTIONS[currentStep], currentStep), currentStep === QUESTIONS.length && React.createElement("div", {
    className: "flex-1 flex flex-col items-center justify-center px-6 text-center"
  }, React.createElement("h2", {
    className: "text-4xl md:text-6xl font-light text-gradient mb-8 tracking-tighter uppercase"
  }, "Ready to send"), React.createElement("p", {
    className: "text-art-muted mb-12 max-w-md leading-relaxed"
  }, "\u3054\u56DE\u7B54\u3042\u308A\u304C\u3068\u3046\u3054\u3056\u3044\u307E\u3057\u305F\u3002", React.createElement("br", null), "\u4E0B\u306E\u30DC\u30BF\u30F3\u3092\u62BC\u3057\u3066\u3001\u63D0\u51FA\u3092\u5B8C\u4E86\u3057\u3066\u304F\u3060\u3055\u3044\u3002"), React.createElement("div", {
    className: "flex flex-col items-center gap-8"
  }, React.createElement("button", {
    onClick: handleSubmit,
    disabled: isSubmitting,
    className: "px-16 py-5 border border-art-accentGreen text-art-accentGreen hover:bg-art-accentGreen hover:text-art-bg transition-all text-xl tracking-widest uppercase disabled:opacity-50"
  }, isSubmitting ? 'SUBMITTING...' : 'SUBMIT'), React.createElement("button", {
    onClick: () => {
      setIsAnimating(true);
      setTimeout(() => {
        setCurrentStep(prev => prev - 1);
        setIsAnimating(false);
      }, 600);
    },
    disabled: isSubmitting,
    className: "text-art-muted hover:text-art-text tracking-widest text-sm transition-colors border-b border-transparent hover:border-art-text pb-1 uppercase"
  }, "\u56DE\u7B54\u3092\u4FEE\u6B63\u3059\u308B (RETURN)"))), currentStep > QUESTIONS.length && React.createElement("div", {
    className: "flex-1 flex flex-col items-center justify-center px-6 text-center"
  }, React.createElement("h2", {
    className: "text-5xl md:text-8xl font-light text-gradient mb-8 tracking-tighter"
  }, "\u3042\u308A\u304C\u3068\u3046\u3054\u3056\u3044\u307E\u3057\u305F"), React.createElement("p", {
    className: "text-art-muted text-lg tracking-widest leading-relaxed"
  }, "\u8CB4\u91CD\u306A\u3054\u610F\u898B\u3092\u3044\u305F\u3060\u304D\u3001\u5FC3\u3088\u308A\u611F\u8B1D\u7533\u3057\u4E0A\u3052\u307E\u3059\u3002", React.createElement("br", null), "\u96C6\u8A08\u5F8C\u3001AI\u306B\u3088\u308B\u5206\u6790\u3092\u884C\u3044\u3001\u7D44\u7E54\u5909\u9769\u306B\u6D3B\u7528\u3055\u305B\u3066\u3044\u305F\u3060\u304D\u307E\u3059\u3002"))), currentStep === -1 && !showOrientation && React.createElement("div", {
    className: "fixed bottom-12 right-12 md:bottom-16 md:right-16 text-right z-40 pointer-events-none"
  }, React.createElement("div", {
    className: "text-art-text font-light tracking-[0.2em] text-sm md:text-base opacity-70"
  }, "WS PARTNERS PTE LTD")), CONFIG !== ERROR_CONFIG && currentStep >= 0 && currentStep < QUESTIONS.length && React.createElement("div", {
    className: "fixed bottom-8 right-8 md:bottom-12 md:right-16 flex gap-4 z-50"
  }, React.createElement("button", {
    onClick: () => {
      if (currentStep > 0) {
        setIsAnimating(true);
        setTimeout(() => {
          setCurrentStep(prev => prev - 1);
          setIsAnimating(false);
        }, 600);
      }
    },
    disabled: currentStep === 0,
    className: "p-4 border border-art-border hover:border-art-accentPeach disabled:opacity-20 rounded-full text-art-text transition-all"
  }, React.createElement(ChevronRight, {
    className: "w-5 h-5 rotate-180"
  })), React.createElement("button", {
    onClick: () => handleNext(),
    className: "p-4 border border-art-border hover:border-art-accentPeach rounded-full text-art-text transition-all"
  }, React.createElement(ChevronRight, {
    className: "w-5 h-5"
  }))), CONFIG !== ERROR_CONFIG && currentStep >= 0 && currentStep < QUESTIONS.length && React.createElement("div", {
    className: "fixed bottom-0 left-0 w-full h-1 bg-white/5 z-50"
  }, React.createElement("div", {
    className: "h-full bg-gradient-art transition-all duration-700",
    style: {
      width: `${currentStep / QUESTIONS.length * 100}%`
    }
  })));
}
const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(React.createElement(App, null));