/**
 * エンジン（JSX）を事前コンパイルする。ブラウザ内Babelは使わない（CDN更新で画面が真っ白になる事故の防止）。
 *
 *   tools/templates/<service>/app.src.jsx  →  tools/templates/<service>/app.js
 * さらに、各サービス配下の全案件フォルダ（index.html を持つ末端）の app.js も、最新エンジンで上書き同期する。
 *
 * 使い方（リポジトリ直下で実行）:
 *   cd tools && npm install        # 初回のみ（@babel/core, @babel/preset-react）
 *   node tools/build.js            # ※リポジトリ直下から。tools/ から実行する場合は node build.js
 *
 * その後 git push でGitHub Pagesに反映。
 */
const fs = require('fs');
const path = require('path');
const babel = require('@babel/core');

const TPL  = path.join(__dirname, 'templates');
const ROOT = path.join(__dirname, '..');
const BANNER = '/* AUTO-GENERATED by build.js — 直接編集しないこと。編集は app.src.jsx を変更し node tools/build.js を再実行 */\n';

function compile(jsxPath) {
  const { code } = babel.transformSync(fs.readFileSync(jsxPath, 'utf8'), {
    presets: [['@babel/preset-react', { runtime: 'classic' }]],
    babelrc: false, configFile: false, comments: false, compact: false,
  });
  if (code.includes('import ') || code.includes('export ')) {
    throw new Error('コンパイル結果に import/export が残っています: ' + jsxPath);
  }
  return BANNER + code;
}

// 末端の案件フォルダ（index.html を持つディレクトリ）を列挙
function findLeafDirs(dir, out = []) {
  if (!fs.existsSync(dir)) return out;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  if (entries.some(e => e.isFile() && e.name === 'index.html')) out.push(dir);
  for (const e of entries) if (e.isDirectory()) findLeafDirs(path.join(dir, e.name), out);
  return out;
}

let n = 0;
for (const service of fs.readdirSync(TPL)) {
  const src = path.join(TPL, service, 'app.src.jsx');
  if (!fs.existsSync(src)) continue;
  const code = compile(src);
  fs.writeFileSync(path.join(TPL, service, 'app.js'), code);
  console.log('compiled: tools/templates/' + service + '/app.js');
  // 同サービス配下の全案件フォルダの app.js を同期
  for (const leaf of findLeafDirs(path.join(ROOT, service))) {
    fs.writeFileSync(path.join(leaf, 'app.js'), code);
    console.log('  synced : ' + path.relative(ROOT, leaf).replace(/\\/g, '/') + '/app.js');
    n++;
  }
}
console.log('\n完了。案件フォルダ ' + n + ' 件の app.js を最新エンジンに同期しました。');
